apiVersion: v1
kind: Service
metadata:
  name: app-python-service
spec:
  selector:
    app.kubernetes.io/name: proxy
  ports:
  - name: app-service-port
    protocol: TCP
    port: 5050
    targetPort: http-service